---
title: "V5MD"
author: "Lexi Chen"
date: "07/02/2022"
output:
  word_document: default
  html_document: default
---
```{r, message=FALSE,warning=FALSE}
rm(list=ls())
# Install and load packages
library(readxl)
library(dmetar)
library(metafor)
library(devtools)
library(dplyr)
library(ape)
library(meta)
library(ggplot2)
library(gtable)
library(grid)
library(ggtree)
library(rotl)
library(webshot)
library(gt)
```

```{r,message=FALSE,warning=FALSE}
## Import collected data
setwd("C:/Users/Lexi C/Desktop/Winter Project/Data collection & analysis") # Setting working directory
Data <- read_excel("Import_data.xlsx") # Import excel file with data
```

```{r,message=FALSE,warning=FALSE}
## Data manipulation
Data$Paper_ID<-as.character(Data$Paper_ID) # changing data type to character
Data$Data_ID<-as.character(Data$Data_ID)
Data$Year_of_publication<-as.character(Data$Year_of_publication)
Data$Sample_size<-as.numeric(Data$Sample_size) # changing data type to numeric
Data$Slope_Value<-as.numeric(Data$Slope_Value)
Data$`R^2(squared_multiple_correlation)`<-as.numeric(Data$`R^2(squared_multiple_correlation)`)
Data$Lower_CI<-as.numeric(Data$Lower_CI)
Data$Upper_CI<-as.numeric(Data$Upper_CI)
Data$S.E.<-as.numeric(Data$S.E.)
Data$t_value<-as.numeric(Data$t_value)
Data$No._of_parameters<-as.numeric(Data$No._of_parameters)
Data$df<-as.numeric(Data$df)
Data$Effect_size<-as.numeric(Data$Effect_size)
Data$SE_of_effect_size<-as.numeric(Data$SE_of_effect_size)
Data <- subset(Data,Data$`SE_of_effect_size`!= "NA") # exclude paper with no data
Data<-mutate(Data,var_r=(SE_of_effect_size)^2) #calculate the effect size variance
```

```{r}
## Check for distribution of all data
Data<-as.data.frame(Data)
hist(Data$Effect_size,xlab = "Effect Size", main = "All effect sizes") # Plot a histogram to examine the distribution of data
```

```{r,warning=FALSE}
## Conduct Phylogenetic meta-analysis using {metafor} 
# get a tree for all the bird species in my data using {rotl}
taxa<-c("Acrocephalus arundinaceus",
        "Acrocephalus sechellensis",
        "Apus melba",
        "Chlamydotis undulata",
        "Coloeus monedula",
        "Cyanistes caeruleus",
        "Diomedea exulans",
        "Malurus cyaneus",
        "Passer domesticus",
        "Phalacrocorax aristotelis",
        "Phoebastria immutabilis",
        "Plocepasser mahali",
        "Sterna hirundo",
        "Sula nebouxii",
        "Taeniopygia guttata",
        "Thalassarche melanophris",
        "Troglodytes aedon")
taxa<-tnrs_match_names(taxa,context_name = "Animals") # use the OTL synthesis tree to relate these species. First need to find Open Tree Taxonomy (OTT) IDs for each species. We can do that with the Taxonomic Name Resolution Service function.
taxon_map<-structure(taxa$search_string,names=taxa$unique_name) #  create a named vector that maps the names we have for each species to the names Open Tree uses for them
# Get a tree
tr <- tol_induced_subtree(ott_id(taxa)[is_in_tree(ott_id(taxa))])
plot(tr)
# remove the extra information from the tip labels (the ott_id), With the IDs removed, we can use our taxon map to replace the tip labels in the tree with the species names from dataset
otl_tips <- strip_ott_ids(tr$tip.label, remove_underscores = TRUE)
tr$tip.label <- taxon_map[ otl_tips ]
# remove the node labels 
tr$node.label <- NULL
plot(tr)
```

```{r, warning=FALSE}
# make a correlation matrix (a relatedness matrix among species)
tree<-compute.brlen(tr) # computes branch lengths of a tree
Phylomatrix<-vcv(tree,cor=T) # computes the expected phylogeny variances and co-variances of a continuous traits assuming it evolves under a given model
Data[,"Phylogeny"]<-tolower(Data$Phylogeny) # translate characters in character vectors (from upper to lower case)
```

```{r,warning=FALSE}
## Running 'multilevel' meta-analysis with linear effect sizes
model <- rma.mv(yi=Effect_size,
                     V=var_r,
                     slab=Author,
                     data=Data,
                     random = list(~1|Data_ID,
                                   ~1|Author,
                                   ~1|Species, # non-phylo effect
                                   ~1|Phylogeny), # phylo effect
                     R=list(Phylogeny=Phylomatrix), # phylogenetic relatedness
                     method="REML", # can produce unbiased estimates of variance and covariance parameters
                     test="t") # using t dist rather than z because t is a better, more conservative distribution than z
summary(model)

# extracting the mean, 95% confidence intervals and 95% prediction intervals
metaanalytic.mean.model.r <- predict(model, digits=3)
```

```{r}
## Calculating heterogeneity for the random effects
model$sigma2
within_study_variance <- sum((1/Data$var_r)*(14-1))/((sum(1/Data$var_r))^2-sum((1/Data$var_r)^2)) 
within_study_variance # 9.222487e-05
sigma_total <- 5.218125e-03+1.067884e-02+2.623742e-02+1.400252e-10+9.222487e-05
sigma_total # 0.04222661
I2species<- 2.623742e-02/sigma_total
I2species # 0.621348
I2between_study<-1.067884e-02/sigma_total
I2between_study # 0.2528936
I2within_study<-5.218125e-03/sigma_total
I2within_study # 0.1235743
H2phylogenetic_heritability<- 1.400252e-10/(1.400252e-10+2.623742e-02+1.067884e-02+5.218125e-03)
H2phylogenetic_heritability # 3.3233e-09
I2total<-I2species+I2between_study+I2within_study+H2phylogenetic_heritability # 0.997816

# creating a data.frame with the meta-analytic mean and heterogeneity estimates
table.model.r <- data.frame(Variables = c("Between-estimate","Between-study","Species","Phylogeny"),
                            Variance = c(0.0052,0.0107,0.0262,0),
                            Heterogeneity = c(12.4,25.3,62.1,0)
)

table.model.r1 <- data.frame(n=length(unique(Data$Author)),
                            k=nrow(Data),
                            mean=round(metaanalytic.mean.model.r[[1]],2),
                            CI=paste0("[",round(metaanalytic.mean.model.r[[3]],2),",",round(metaanalytic.mean.model.r[[4]],2),"]"),
                            PI=paste0("[",round(metaanalytic.mean.model.r[[5]],2),",",round(metaanalytic.mean.model.r[[6]],2),"]"),
                            I2_Total=round(I2total*100,1),
                            I2_Data_ID=round(I2within_study*100,1),
                            I2_Author=round(I2between_study*100,1),
                            I2_Species=round(I2species*100,1), 
                            I2_Phylogeny=round(H2phylogenetic_heritability*100,1)
)

# creating a nicely-formatted table using the R package 'gt'
table.model.r.gt <- table.model.r %>% # align data into table
  gt::gt() %>% 
  cols_label(Variables=md("**Random effects**"), # set column names
             Variance=md("**Variance**"),
             Heterogeneity=md("**Heterogeneity *I*<sup>2</sup></sub>\n(%)</sub>**")
  ) %>%
  cols_align(align = "center") %>% # make all text center
  tab_source_note(source_note = md("*Number of studies = 21; Number of estimates = 91")) # footnotes for the table

# tab_options(table.width=770)
table.model.r.gt
gtsave(table.model.r.gt,"table2.pdf")
```

```{r}
# Create forest plot for the summary effect
pooled_data<-data.frame(Overall_effect_size="Overall summary effect",Effect_size=0.0178,Lower_CI=-0.0774,Upper_CI=0.1131)
ggplot(data=pooled_data,aes(y=Overall_effect_size,x=Effect_size,xmin=Lower_CI,xmax=Upper_CI))+
  geom_point(size=2.5)+
  geom_errorbarh(height=.1) +
  labs( x='Effect Size',y=element_blank()) +
  geom_vline(xintercept=c(-0.1,-0.05,0,0.05,0.1,0.15), colour='grey')+
  geom_vline(xintercept=0, color='black', linetype='dashed', alpha=1) +
  xlim(-0.1,0.15)+
  theme_classic()
```

```{r}
## running model with moderators
model.full <- rma.mv(yi=Effect_size,
                     V=var_r,
                     slab=Author,
                     data=Data,
                     mods = ~ Social_mating_system + When_in_offspring_life_effect_was_measured + Fitness + Type_of_transmissions + Species,
                     random = list(~1|Data_ID,~1|Author,~1|Phylogeny),
                     R=list(Phylogeny=Phylomatrix),
                     method="REML",
                     control=list(optimizer="optim"))
summary(model.full)
```

```{r}
# Forest plot for for moderator analysis
mating.system<-data.frame(Type=c("Monogamy","Monogamy & polygamy","Polygamy"),Effect_size=c(-0.010402436,-0.024374288,-0.071755547),Lower_CI=c(-0.249575004,-0.315368681,-0.382835285),Upper_CI=c(0.228770131,0.266620105,0.239324191))

life.stage<-data.frame(Type="Lifetime",Effect_size=0.111141252,Lower_CI=-0.15342635,Upper_CI=0.375708853)

fitness<-data.frame(Type=c("LRS","Proxy","Survival","TL","Weight"),Effect_size=c(-0.031155326,0.004423241,-0.04742342,-0.034962996,-0.05995307),Lower_CI=c(-0.156923296,-0.138263827,-0.182870677,-0.202127033,-0.195705957),Upper_CI=c(0.094612644,0.147110309,0.088023836,0.13220104,0.075799816))

transmissions<-data.frame(Type=c("Extra-pair genetic father : son","Extra-pair social father","Extra-pair social father : son","Father : daughter","Father : son","Foster father","Foster mother","Maternal","Mixed","Mother : Daughter","Mother : son","Paternal","Within-pair father","Within-pair father : son"), Effect_size=c(-0.015504398,-0.009069553,-0.006440937,0.098074011,0.000241556,0.012342463,0.036398655,-0.023702225,-0.322312793,-0.106266064,0.037107915,-0.063485185,0.024324626,0.049722131), Lower_CI=c(-0.22723478,-0.176549474,-0.218175615,-0.127954507,-0.229445216,-0.180469411,-0.165076763,-0.184194592,-0.64157947,-0.332042518,-0.146694322,-0.232584527,-0.143157739,-0.16200965), Upper_CI=c(0.196225985,0.158410367,0.205293741,0.324102529,0.229928329,0.205154338,0.237874073,0.136790141,-0.003046117,0.11951039,0.220910151,0.105614158,0.191806991,0.261453912))

Species<-data.frame(Type=c("Black-browed albatross","Blue-footed booby","Blue tit","Common terns","European shag","Great reed warbler","Houbara bustard","House sparrows","Jackdaws","Laysan albatross","Seychelles warbler","Wandering albatross","White-browed sparrow weaver","Zebra finch"), Effect_size=c(0.707474887,-0.018225711,0.055896791,-0.051675939,0.059004543,0.274554986,-0.279020203,-0.131254945,0.007022564,0.460178568,-0.08240739,0.081061089,0.557464473,0.018836849), Lower_CI=c(0.360131345,-0.350070618,-0.123365451,-0.284495262,-0.139990786,-0.022040808,-0.524245576,-0.405347724,-0.173507166,0.077129381,-0.46546565,-0.096890598,0.178331699,-0.330272026), Upper_CI=c(1.054818428,0.313619196,0.235159033,0.181143384,0.257999871,0.571150779,-0.03379483,0.142837833,0.187552295,0.843227755,0.300650871,0.259012775,0.936597248,0.367945724))

g1<-ggplot(data=mating.system,aes(y=Type,x=Effect_size))+
  geom_point(size=1)+
  geom_errorbarh(aes(xmin=Lower_CI,xmax=Upper_CI),height=.3) +
  scale_y_discrete(labels=mating.system$Type)+
  geom_vline(xintercept=c(-0.75,-0.5,-0.25,0,0.25,0.5), colour='lightgrey')+
  geom_vline(xintercept=0, color='black', linetype='dashed', alpha=1) +
  ylab("Social mating system")+
  xlab("")+
  theme_classic()

g2<-ggplot(data=life.stage,aes(y=Type,x=Effect_size))+
  geom_point(size=1)+
  geom_errorbarh(aes(xmin=Lower_CI,xmax=Upper_CI),height=.05) +
  scale_y_discrete(labels=life.stage$Type)+
  geom_vline(xintercept=c(-0.75,-0.5,-0.25,0,0.25,0.5), colour='lightgrey')+
  geom_vline(xintercept=0, color='black', linetype='dashed', alpha=1) +
  ylab("Life stage at fitness measurement")+
  xlab("")+
  theme_classic()

g3<-ggplot(data=fitness,aes(y=Type,x=Effect_size))+
  geom_point(size=1)+
  geom_errorbarh(aes(xmin=Lower_CI,xmax=Upper_CI),height=.3) +
  scale_y_discrete(labels=fitness$Type)+
  geom_vline(xintercept=c(-0.75,-0.5,-0.25,0,0.25,0.5), colour='lightgrey')+
  geom_vline(xintercept=0, color='black', linetype='dashed', alpha=1) +
  ylab("General fitness measures")+
  xlab("Effect size")+
  theme_classic()

g4<-ggplot(data=transmissions,aes(y=Type,x=Effect_size))+
  geom_point(size=1)+
  geom_errorbarh(aes(xmin=Lower_CI,xmax=Upper_CI),height=.5) +
  scale_y_discrete(labels=transmissions$Type)+
  geom_vline(xintercept=c(-0.75,-0.5,-0.25,0,0.25,0.5), colour='lightgrey')+
  geom_vline(xintercept=0, color='black', linetype='dashed', alpha=1) +
  ylab("Type of transmissions")+
  xlab("Effect size")+
  theme_classic()
# combine the forest plots part 1
g1<-ggplotGrob(g1)
g3<-ggplotGrob(g3)
g.1<-rbind(g1,g3)
g.1$widths <- unit.pmax(g1$widths,g3$widths)
grid.newpage()
grid.draw(g.1)
ggsave(g.1,file="forest1.pdf")
# combine the forest plots part 2
g4<-ggplotGrob(g4)
g2<-ggplotGrob(g2)
g.2<-rbind(g2,g4)
g.2$widths <- unit.pmax(g2$widths,g4$widths)
grid.newpage()
grid.draw(g.2)
ggsave(g.2,file="forest2.pdf")
```

```{r}
# get a tree for all the bird species in my data using {rotl}
taxa2<-c("Acrocephalus arundinaceus",
        "Acrocephalus sechellensis",
        "Chlamydotis undulata",
        "Coloeus monedula",
        "Cyanistes caeruleus",
        "Diomedea exulans",
        "Passer domesticus",
        "Phalacrocorax aristotelis",
        "Phoebastria immutabilis",
        "Plocepasser mahali",
        "Sterna hirundo",
        "Sula nebouxii",
        "Taeniopygia guttata",
        "Thalassarche melanophris")
taxa2<-tnrs_match_names(taxa2,context_name = "Animals")
taxon_map2<-structure(taxa2$search_string,names=taxa2$unique_name) #  create a named vector that maps the names we have for each species to the names Open Tree uses for them
# Get a tree
tr2 <- tol_induced_subtree(ott_id(taxa2)[is_in_tree(ott_id(taxa2))])
plot(tr2)
# remove the extra information from the tip labels (the ott_id), With the IDs removed, we can use our taxon map to replace the tip labels in the tree with the species names from dataset
otl_tips2 <- strip_ott_ids(tr2$tip.label, remove_underscores = TRUE)
tr2$tip.label <- taxon_map[ otl_tips2 ]
# remove the node labels 
tr2$node.label <- NULL
# to capitalize genus names in the phylogeny tree
foo<-function(x){
   x<-strsplit(x,split="")[[1]]
   x[1]<-toupper(x[1])
   x<-paste(x,collapse="")
}
tr2$tip.label<-sapply(tr2$tip.label,foo,USE.NAMES=FALSE)
plot(tr2)

# Align phylogenetic tree with forest plot with 'species' as a moderator

d1<-data.frame(Species = tr2$tip.label, Effect_size = c(0.018836849,0.557464473,-0.131254945,0.274554986,-0.08240739,0.055896791,0.007022564,-0.051675939,0.059004543,-0.018225711,0.081061089,0.460178568,0.707474887,-0.279020203), Lower_CI = c(-0.330272026,0.178331699,-0.405347724,-0.022040808,-0.46546565,-0.123365451,-0.173507166,-0.284495262,-0.139990786,-0.350070618,-0.096890598,0.077129381,0.360131345,-0.524245576), Upper_CI = c(0.367945724,0.936597248,0.142837833,0.571150779,0.300650871,0.235159033,0.187552295,0.181143384,0.257999871,0.313619196,0.259012775,0.843227755,1.054818428,-0.03379483))
# Visualizing phylogenetic tree and heterogenous associated data
tree<-ggtree(as.phylo(tr2))+geom_tiplab()
ggtree(as.phylo(tr2))+geom_tiplab()+xlim_tree(15)

g3<-facet_plot(tree,panel="Forest plot",data = d1,geom=geom_point,aes(x=Effect_size),stat= 'identity') + ggtree::xlim_expand(xlim=c(-1,1.5),panel="Forest plot") # Create a plot with tree on the left and forest plot on the right
g3
g4<-g3 + xlim_tree(25) + xlim_expand(xlim=c(-0.5,0.5), panel = "Forest plot") + # adjust the size of the tree
  theme_tree2()
g4
g5<-facet_plot(g4,geom = geom_errorbarh, data=d1,aes(x=Effect_size,xmin=Lower_CI,xmax=Upper_CI),panel = "Forest plot") # add error bars on the forest plot
g5
d=data.frame(x=c(-1,-0.5,0,0.5,1,1.5),.panel='Forest plot')
g6<-g5+geom_vline(data=d,aes(xintercept=x),color = "grey") # add vertical lines onto the forest plot
d2=data.frame(x=0,.panel='Forest plot')
g7<-g6+geom_vline(data=d2,aes(xintercept=x),linetype = "dotted") # add vertical lines onto the forest plot
g7
ggsave(g7,file="forest3.pdf")
```

```{r}
# plot a funnel plot for publication bias
funnel(model.full,yaxis = "seinv",xlab = "Effect size")
```

```{r}
# Egger's regression test
publication.bias.model.r.all.se <- rma.mv(yi=Effect_size, 
                                          V=var_r,
                                          mods=~-1+ # -1 removes the intercept
                                          SE_of_effect_size + Social_mating_system + When_in_offspring_life_effect_was_measured + Fitness + Type_of_transmissions + Species,
                                          random = list(~1|Data_ID,
                                                        ~1|Author,
                                                        ~1|Phylogeny),
                                          R=list(Phylogeny=Phylomatrix),
                                          method="REML",
                                          test="t", 
                                          data=Data)
summary(publication.bias.model.r.all.se)
# plot a graph for Egger's regression test
publication<-ggplot(Data,aes(x=SE_of_effect_size,y=Effect_size),ylim(0,0.15))+
  geom_point()+
  geom_abline(intercept = publication.bias.model.r.all.se$b[1],slope = publication.bias.model.r.all.se$b[2])+ # Add regression line
  geom_hline(yintercept=0,linetype=2,color="darkgrey")+
  scale_x_continuous(n.breaks=15)+
  labs(x="Standard error (precision)",y="Effect size")+
  theme_bw() + # Apply black and white theme
  theme(legend.position = "none") # Remove legend
ggsave("publication.pdf")
```

```{r}
# Time-lag bias test
Data$Year_of_publication<-as.numeric(Data$Year_of_publication)
time.lag.bias.model.r.all.se <- rma.mv(yi=Effect_size, V=var_r,
                                          mods=~1+
                                          Year_of_publication,
                                          R=list(Phylogeny=Phylomatrix),
                                          method="REML",
                                          test="t", # using t dist rather than z
                                          data=Data)
summary(time.lag.bias.model.r.all.se)
# plot a graph for time-lag bias test
time<-ggplot(Data,aes(x=Year_of_publication,y=Effect_size),ylim(2008,2021),cex.axis = 1)+
  geom_point(size=1)+
  geom_abline(intercept = time.lag.bias.model.r.all.se$b[1],slope = time.lag.bias.model.r.all.se$b[2])+
  theme_bw() + # Apply black and white theme
  ylim(-0.5,0.8)+
  theme(legend.position = "none")+ # Remove legend
  scale_x_continuous(n.breaks=14)+
  geom_hline(yintercept=0,linetype=2,color="darkgrey")+
  labs(x="Year of publication",y="Effect size")+
  theme_bw()
ggsave("time.pdf")
```
```{r}
# Export dataset in R
write.csv(Data,file="Data_R.csv")
```